### ISSUE TITLE
Explicitly provide DATABASE_URL to Prisma

### ISSUE THREAD

**Issue by sodic** [wasp-lang/wasp#940] opened 2023-01-08 00:26 UTC
When we run `wasp db migrate-dev`, Prisma correctly picks up database URL that we specified in `DATABASE_URL` env var. However, we realized that we specify this URL inside `.env.server`, and only explicitly read it when actually running the server, meaning we don't provide it to prisma when running `wasp db migrate-dev`, so how does it pick it up!?

Turns out that Prisma is "smart", in a way that it searches for .env files in the vicinity on its own, and it finds .env.server and reads it from it! This is what their docs say.

Instead of relying on Prisma to do this, which is pretty fragile and bound to cause problems down the road, we should instead make this more explicit and make sure that we are the ones providing it to Prisma. Btw this is not just for `migrate-dev`, but any commands that directly use Prisma, `wasp db studio`.

**Comment by shayneczyzewski** [comment] 2023-01-12 14:33
This may not be a problem after all. Our `.server.env` gets built as`.wasp/out/server/.env` Prisma explicitly notes support for this: https://www.prisma.io/docs/guides/development-environment/environment-variables#using-env-files

**Comment by infomiho** [comment] 2024-07-25 11:40
Shayne was correct here and this is expected behaviour from Prisma: https://www.prisma.io/docs/orm/more/development-environment/environment-variables/env-files

I'm closing this issue since everything works as expected.

**Closed by infomiho** 2024-07-25 11:40 UTC
Labels: bug, haskell, prisma
