### ISSUE TITLE
Todo App Step 7 Issue

### ISSUE THREAD

**Issue by pwilson0** [wasp-lang/wasp#1324] opened 2023-07-16 03:34 UTC
Hi all,

I'm working through the Wasp "TodoApp" tutorial, and reached an error that prevented me from moving forward on this page: https://wasp-lang.dev/docs/tutorials/todo-app/07-dependencies

When I went to add the dependencies line within my main.wasp file within the app block...

```
  dependencies: [
    ("react-clock", "4.2.0")
  ]
```

VS Code highlighted this as an issue (maybe the WLS is out of date?) and the app refused to compile, so I couldn't go forward. I checked the other documentation page on dependencies (https://wasp-lang.dev/docs/language/features#dependencies) to make sure the formatting looked right, and it seemed to agree with the tutorial minus the leading ^ on dependency versions in the documentation.

In the course of fooling around with this trying to move past the issue, I did `npm install react-clock` from the terminal and removed the dependencies section from the app block in the main.wasp file and that seemed to solve my problem. The react-clock renders where I placed it in the MainPage.jsx file, and I no longer have compiler warnings.

Hope this helps! I have essentially zero modern development experience, so I'm kind of feeling my way along blindly here. If I've gone off course in some way please accept my apologies for the noise.

**Comment by Martinsos** [comment] 2023-07-21 12:17
Hey @pwilson0 thanks for the issue!

The code block you pasted is looking good. You said VSCode highlighted this as an issue -> do you have an error message possibly that you could share?

Dependencies are pretty old feature so I don't think WLS is out of date -> it actually can't be out of date also because it is packed together with the `wasp` CLI, so we can eliminate that as the cause.
What I am thinking might be the cause is that you didn't add `,` at the end of the line before `dependencies`, could that be possible?

The thing you did with installing them via `npm` was smart :D, but from the Wasp perspective it is a "hack" that will cause problems down the road, so you don't really want to do that.

Btw in the next months we will release new version of Wasp that will make dependencies installation go via `npm`, so much more "normal", so your approach will become valid then.

**Comment by Martinsos** [comment] 2023-07-24 10:11
@pwilson0 closing this one for now, but please feel free to comment if issue still persists and I will reopen!

**Closed by Martinsos** 2023-07-24 10:11 UTC
