### ISSUE TITLE
The best way to implement support a sign up form with extra fields?

### ISSUE THREAD

**Issue by matijaSos** [wasp-lang/wasp#1103] opened 2023-04-04 14:37 UTC
This has already been mentioned a few times; here's an example (https://app.loops.so/register):
![Screenshot 2023-04-04 at 16 30 40](https://user-images.githubusercontent.com/1536649/229825609-f8d2d55d-fc17-4001-aaac-cf524b3ed86a.png)

How should we go about this? Next to this, one way is to implement it separately (so after user registers, the first screen in the app asks additional questions). The question is also how to make it work with social login (e.g. Google or GitHub).

**Comment by infomiho** [comment] 2023-08-30 08:27
Duplicate of #1233

**Closed by infomiho** 2023-08-30 08:27 UTC
Labels: enhancement, question, hm, webdev
