### ISSUE TITLE
wrong url after deployment

### ISSUE THREAD

**Issue by alanzou** [wasp-lang/wasp#2214] opened 2024-07-31 14:16 UTC
**Describe the bug**
Visit your newly deployed app at https://aixlt-admin-client-divine-wind-5803.fly.dev/

                    __
                   // \
                   \\_/ //
             _    -(||)(')
            \ \____///_____
   #########[==__DEPLOYED__}
            /_/

  
🚀  Client has been deployed! Your Wasp app is accessible at: https://aixlt-admin-divine-wind-5803-client.fly.dev 

wasp gave second url which is wrong.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Martinsos** [comment] 2024-08-14 19:16
This sounds familiar to me: I believe that this happens only in some cases, e.g. when name is taken so fly adds this extra part to it and then our idea of where `-client` goes is wrong. We should look to fix this in the Fly deployment script.

**Comment by infomiho** [comment] 2024-08-19 11:39
Duplicate of https://github.com/wasp-lang/wasp/issues/1588

**Closed by infomiho** 2024-08-19 11:39 UTC
Labels: bug, deployment
