### ISSUE TITLE
Make Wasp smarter when writing over existing generated files (e.g. delete redundant(old) files)

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/wasp#209] opened 2021-04-14 18:21 UTC
Wasp compiles source and generates code in outDir.
But, it does not clear the ourDir first -> instead it just generates the code over whatever is already there, meaning there might be some left-over files that shouldn't exist any more.
This wasn't a problem so far, since redundant files were just not used by the rest of the code.
However, it starting being a problem with .env file, because if you remove .env from Wasp project, the old one remains in the generated project, and env vars from it area loaded while they shouldn't be.

For now we did a quick fix -> we just delete .env file from the generated directory before we generate new code.

Advanced approach would be to, before actually writing file drafts to disk, generate a list of files that are to be created together with their checksums. Then, we can use that list to compare it to the previous list (that we generated the last time we generated code and we persisted it in helper file next to the generated code) and we can do fancy stuff like:
- Delete all the files that were on the previous list but are not any more.
- Not write files that have not changed (that have the same checksum as before), to avoid unnecessary writes to disk.

This means that we need a way to generate this list before actually writing the file drafts to the disk.
I think the best way to do this is to add additional method to Writeable, that is somewhat of a "dry run" method -> it does not write anything to disk, instead it tells us path of where it wants to write + the checksum of the file that it would write. It would probably need to do some IO operations like reading for this, but it will not write anything. This can then be used to construct the list, and then actual `write` method can be used to finally execute the drafts that need to be executed (many of them will not be needed to be executed because they will not change).

Once we do this, we can probably remove `preCleanup` method from the ServerGenerator.hs.

**Comment by shayneczyzewski** [comment] 2021-12-09 16:03
@Martinsos and I met today for our first pair programming session to start work on this (woot! 🎉  was fun). WIP captured on this branch: https://github.com/wasp-lang/wasp/tree/shayne-martin-smart-file-generator

We decided a good first milestone would be to simply persist the output file path and checksum information of the `FileDrafts` in the to-be generated web app, without any logic about if we _should_ actually be writing (or deleting) things. That can come later.

For this first session:
- defined the first milestone and chatted about implementation options, deciding on tracking via a tuple of `IO (Checksum, Path' (Rel ProjectRootDir) File')` for each `FileDraft` (via `Writeable`)
- we added a new dependency to calculate the checksum (cryptohash-sha256) https://hackage.haskell.org/package/cryptohash-sha256
- added a new function (provisionally called `dryRun`) to the `Writeable` Type Class
- added the instance implementation of `dryRun` for `FileDraft`, `TextFileDraft`, and `CopyFileDraft`

For the next session, we will try to:
- add the instance implementation of `dryRun` for `TemplateFileDraft`, by applying the parameters to the template itself and checksumming the result
- persist the output of `dryRun` for all `FileDrafts` to disk in `Wasp.Generator`

**Comment by shayneczyzewski** [comment] 2021-12-16 17:36
In the second phase of this, @Martinsos and I did the following:
- Implemented `dryRun` for `TemplatFileDraft`, and then refactored it so the boilerplate of `Maybe` extraction can be shared by `write` and `dryRun` (learned about `TupleSections` too! 🥳 )
- Removed duplicated checksum calculations from all three `FileDraft` types and added two new functions (`checksumFromString`, `checksumFromText`) to `Wasp.Util` (and moved the `Data` declaration of `Checksum` there too)
- Started refactor of `Wasp.Generator.writeWebAppCode` to process a list of `FileDraft`s more cleanly, and wrote start of `writeChecksumFile`

One of the things we demonstrated is we cannot do `Data.Aeson.encode` on a `[(Checksum, Path' (Rel ProjectRootDir) File')]` since `StrongPath` is not "encodable", however, if we map over and convert SPs to `String` we can then call encode on `[(Checksum, String)]`. TBD on what the actual JSON output is though of a List of Tuples (perhaps array of arrays?).

In the excitement of trying to print that to the screen to find out just before ending, we got the following error:
```
wasp-cli: /Users/shayne/dev/wasp/waspc/.stack-work/install/x86_64-osx/62ed3fbc25fdee2d639dad0c2feb0f07109db53a740ee6c31fcfc5dc5ea6a430/8.10.7/share/x86_64-osx-ghc-8.10.7/waspc-0.2.2.2/Generator/templates/react-app/public/favicon.ico: hGetContents: invalid argument (invalid byte sequence)
```

The plan for next week is to investigate the lazy IO hGetContents problem and solve it. Could potentially be multiple opens where second is failing, or some sequence of open -> open (but does not fail) -> close -> read (this fails) based on the lazy semantics of open not closing until the full contents are read and how `dryRun` and `write` are interacting.

https://stackoverflow.com/questions/43910682/haskell-hgetcontents-error

Possible solution is to use strict IO but then we lose streaming capabilities.

**Comment by Martinsos** [comment] 2021-12-16 18:22
> In the second phase of this, @Martinsos and I did the following:
> 
> * Implemented `dryRun` for `TemplatFileDraft`, and then refactored it so the boilerplate of `Maybe` extraction can be shared by `write` and `dryRun` (learned about `TupleSections` too! partying_face )
> * Removed duplicated checksum calculations from all three `FileDraft` types and added two new functions (`checksumFromString`, `checksumFromText`) to `Wasp.Util` (and moved the `Data` declaration of `Checksum` there too)
> * Started refactor of `Wasp.Generator.writeWebAppCode` to process a list of `FileDraft`s more cleanly, and wrote start of `writeChecksumFile`
> 
> One of the things we demonstrated is we cannot do `Data.Aeson.encode` on a `[(Checksum, Path' (Rel ProjectRootDir) File')]` since `StrongPath` is not "encodable", however, if we map over and convert SPs to `String` we can then call encode on `[(Checksum, String)]`. TBD on what the actual JSON output is though of a List of Tuples (perhaps array of arrays?).
> 
> In the excitement of trying to print that to the screen to find out just before ending, we got the following error:
> 
> ```
> wasp-cli: /Users/shayne/dev/wasp/waspc/.stack-work/install/x86_64-osx/62ed3fbc25fdee2d639dad0c2feb0f07109db53a740ee6c31fcfc5dc5ea6a430/8.10.7/share/x86_64-osx-ghc-8.10.7/waspc-0.2.2.2/Generator/templates/react-app/public/favicon.ico: hGetContents: invalid argument (invalid byte sequence)
> ```
> 
> The plan for next week is to investigate the lazy IO hGetContents problem and solve it. Could potentially be multiple opens where second is failing, or some sequence of open -> open (but does not fail) -> close -> read (this fails) based on the lazy semantics of open not closing until the full contents are read and how `dryRun` and `write` are interacting.
> 
> https://stackoverflow.com/questions/43910682/haskell-hgetcontents-error
> 
> Possible solution is to use strict IO but then we lose streaming capabilities.

Just a bit more info on error we got, possibly reiterating some what you wrote Shayne but shouldn't hurt:

So with lazy IO, if you do content <- openFile, it basically opens files on the disk and then leaves it open until Haskell actually consumes the whole content  String. So for example, if you do head content after that, that will consume only a bit of file, just one character, and file remains open on disk. And this is cool, but for example if in the meantime you try to open it again, then you get problems because it is already open!
One solution is to just use strict IO -> there are strict versions of these functions, so we can be sure in that case that content <- openFile actually opens, reads and closes the file as part of that one IO action.
But, then we use the possible cool effects of automatic "streaming". So, we could instead try to think deeper into why is laziness causing us the problems (is it because we try to open same files multiple times? once with write and once with dryRun?) -> maybe we can think through it and figure out how to make it work in lazy way. But, if that proves too complicated we can always go the strict route.

**Comment by shayneczyzewski** [comment] 2021-12-23 18:38
In this Holiday Hippo 🎄 🦛  version of pair programming with @Martinsos :D we successfully completed phase 1! 🥳  This is the step of calculating the checksums for all `FileDraft`s to be written and persisting this information as JSON file on disk stored in the file: `.wasp/out/.waspchecksums`

Coming into today, we briefly glanced at the error thinking we hit a lazy IO issue due to the reference to `hContents`, but thankfully Martin suggested we check the error one more time and he rightfully identified the actual issue: we were reading the input file incorrectly! The error hit while we were reading in a `favicon.ico`. We needed to actually read the input file as a `ByteString` since it could be binary data, not just a `String` like we were. We updated this and added a `checksumFromByteString` helper function.

From there, we could now read the input files and calculate the checksums without error, however our checksum outputs included the UTF-8 Unicode escape codes in the string. This was due to our use of `Data.ByteString.UTF8.toString` on the output of `SHA256.hash`, which was then `show`n with escapes. The trick to put it in an ASCII friendly hex version of the string was a StackOverflow win:

```haskell
bytestringToHex :: B.ByteString -> Hex
bytestringToHex = Hex . concatMap (printf "%02x") . B.unpack
```

This just uses `printf` to format the raw bytes as 0-padded, 2-digit hex. We also added a test.

Finally, it was time to use `aeson-pretty` to write a nicely formatted JSON array of arrays to disk. Here is a sample of the output format:

```javascript
[
    [
        "aa1bd54732b015158d24c55e03bc79b2f211109bc2b0478d6f2ad6b52d15847f",
        "web-app/README.md"
    ],
    [
        "957e98c79e0d021dd3a21f2bce313bc58c164723d78172918577a032f8764bf5",
        "web-app/package.json"
    ],
    [
        "d373417ea2a8844e3b7a1515aab123e90fbeb4b7225144d55d243d9f6f04f73a",
        "web-app/.gitignore"
    ],
    ...
]
```

During our next session in 2022 we will need to revisit the existing TODOs, and then start on the fun part: using this structure to determine if we need to write anything new or delete anything old during app generation! 🚀

**Comment by shayneczyzewski** [comment] 2022-01-07 14:07
We need to keep an eye on this PR: https://github.com/wasp-lang/wasp/pull/420 Once we make the Generator responsible for copying the migrations dir down and migrate dev back up, it can invalidate our cache of checksums.

**Comment by shayneczyzewski** [comment] 2022-01-07 16:21
Today was the first 2022 edition 🎆 for @Martinsos and myself, and it was another fun and productive one (albeit with a lower total LOC, which is actually good). We started out initially talking about PR #420 above and how that may impact us. Basically we will need to invalidate our cache somehow after we copy the migrations dir back up.

We then jumped right into the Generator.hs All of our changes today were in that single file. We decided we would need to read our checksums back in, and spent a most of our time on that function. In the end it came out like so:
```haskell
readChecksumFile :: Path' Abs (Dir ProjectRootDir) -> IO (Maybe [(Path' (Rel ProjectRootDir) File', Checksum)])
readChecksumFile dstDir = do
  -- TODO: make sure file exists and return Nothing if it does not
  contents <- BSL.readFile (SP.fromAbsFile $ dstDir </> checksumFileInProjectRoot)
  return $ do
    checksumsAndFPs <- Aeson.decode contents :: Maybe [(Checksum, FilePath)]
    sequence $ (\(cs, fp) -> (,cs) <$> SP.parseRelFile fp) <$> checksumsAndFPs
```

The `sequence` step at the bottom was the trickiest part, as we needed a way to go from a list of `(Checksum, FilePath)` tuples into a list of `(StrongPath, Checksum)` tuples where the SP parsing returned a `Maybe`. If decoding fails, or if any file path parsing fails, we want to return `Nothing`.

We then added the following TODOs for next time:
- readChecksumFile
  - make sure file exists and return Nothing if it does not
- writeWebAppCode
  - remove generated project if checksum file missing or invalid (readChecksumFile returns Nothing)
  - remove checksum file (in any case)
  - filter filedrafts where we only write those that are new or changed, and we delete those that are now missing

**Comment by shayneczyzewski** [comment] 2022-01-12 02:48
Chatted through this a bit more with Edsko today @Martinsos, and we had some interesting discussions (both about `ReaderT/ExceptT` Monad transformer stacks and how they can be refactored for even better maintainability/abstraction in other ways). He noted while it is objectively a valid use of `ReaderT` for passing around a `Wasp`, he still felt (possibly due to my mediocre explanations) that his personal preference is for `ReaderT` to be used for singular static things vs different values of some larger type (i.e. only needing some parts of larger entity like `waspElements :: [WaspElement]`). Also, if it is going to be used everywhere down the call stack anyways, and is important to understanding the function's purpose, it lends itself to being included explicitly in the function signature as additional documentation about what it needs to operate on (takes a `Wasp` and returns blah). `ReaderT` more often used for flatter items/mockables/things we don't use all the time at each level. Much of the gains lost when every function will just have to do `wasp <- ask` as first line (vs explicit param). This will also have implications on testing (passing pure args vs constructing contexts). WARNING: I'm 99% sure I'm losing some things in translation. Certainly we can still use as such, and I can see many pros/cons of both sides of the coin, but just wanted to raise as one data point for us to consider/chew on before committing to `ReaderT` with `Wasp`. Possibly worth a quick meeting sync on it sometime as a final 👍🏻 Thanks!

**Comment by Martinsos** [comment] 2022-01-13 20:11
In the latest session we thightened up the `readChecksumFile` function so it checks for non-existence of checksum file, we then also did the checksum clean needed in the `writeWebAppCode`, wrote initial skeleton for the rest of the logic we need in there which is deciding which file drafts need to be written and which files from the disk need to be removed, and we ended up adding `getDstPath` function to the `Writeable` typeclass, since we need that in our logic that I mentioned above!

**Comment by shayneczyzewski** [comment] 2022-01-17 19:13
FYI: I will be squashing and rebasing this branch off master so we can pull in the new `FileDraft` type.

**Comment by shayneczyzewski** [comment] 2022-01-20 17:44
Today, we added `getDstPath :: w -> Path' (Rel ProjectRootDir) File'` to the `Writeable` Type Class, and instances for `FileDraft` and their variants. This enabled us to get started on the logic for writing FDs and deleting files. 🔥 

In order to determine `fileDraftsToWrite`, we needed to find both new FDs that were not yet in the checksum file (`getNewFileDrafts`), as well as FDs that were present tin the checksum file but had a different checksum, and thus changed (`getChangedFileDrafts`).

In order to determine `filesToDelete`, we needed to find any checksum entries that did not have a corresponding FD (`getRedundantGeneratedFiles`).

Next week, we need to implement:
```haskell
deleteFiles :: [Path' (Rel ProjectRootDir) File'] -> IO ()
deleteFiles files = undefined
```

Plus the  `Writeable` functions (`dryRun` and `getDstPath`) for `CopyDirFileDraft`. And then it is off to wrapping up the TODOs (mainly comments, refactoring, and tests). 🚀

**Comment by Martinsos** [comment] 2022-01-20 21:06
> Today, we added `getDstPath :: w -> Path' (Rel ProjectRootDir) File'` to the `Writeable` Type Class, and instances for `FileDraft` and their variants. This enabled us to get started on the logic for writing FDs and deleting files. fire
> 
> In order to determine `fileDraftsToWrite`, we needed to find both new FDs that were not yet in the checksum file (`getNewFileDrafts`), as well as FDs that were present tin the checksum file but had a different checksum, and thus changed (`getChangedFileDrafts`).
> 
> In order to determine `filesToDelete`, we needed to find any checksum entries that did not have a corresponding FD (`getRedundantGeneratedFiles`).
> 
> Next week, we need to implement:
> 
> ```haskell
> deleteFiles :: [Path' (Rel ProjectRootDir) File'] -> IO ()
> deleteFiles files = undefined
> ```
> 
> Plus the `Writeable` functions (`dryRun` and `getDstPath`) for `CopyDirFileDraft`. And then it is off to wrapping up the TODOs (mainly comments, refactoring, and tests). rocket

The main part is done, now for the other 80% :D :P.

**Comment by shayneczyzewski** [comment] 2022-01-20 21:33
Haha yes exactly!

**Comment by shayneczyzewski** [comment] 2022-01-27 17:59
As we started on the "remaining 80% today" :D we got off to a quick win, implementing `deleteFiles` in about two minutes.

![giphy](https://user-images.githubusercontent.com/523636/151414500-bcd58250-bfd1-4715-85de-dd7f97170e47.gif)

We then switched over and wanted to implement the new `Writeable` functions (`dryRun` and `getDstPath`) for `CopyDirFileDraft`, and this is where the dragon appeared 🐲 . Both of those functions had types for relative **_file_** paths. NOOOOO

![giphy (1)](https://user-images.githubusercontent.com/523636/151414808-8fe70d93-f0fd-40e9-87c5-5875b2847012.gif)

To be fair, we did know ahead of time we would have to treat Files and Directories differently at some point, but confirmed we are ok keeping a directory notion included as a `FileDraft` and handle the differences here (in a more limited scope).

> Aside: The reason we added `CopyDirFileDraft` to begin with was so the Generator could manage the migrations directory. This allows us to copy a directory into the generated project. The other option is to produce a list of `FileDrafts` in the directory, but that would force us into IO and it is preferable to keep the Generator and its functions as pure as possible. The idea of copying directories will be used in other instances in the future I'm sure, and we took the if you squint hard enough like Linux does, "everything is a file" approach.

So we had to start by handling both cases in `Writeable` somehow. To encode it in the type system , we added a new type called:

```haskell
type FileOrDirPathRelativeTo a = Either (Path' (Rel a) File') (Path' (Rel a) Dir')
```

and used `FileOrDirPathRelativeTo ProjectRootDir` in the return type for both `dryRun` and `getDstPath` instead of `File'`. From there, most of the updates to the other `FileDraft` types were easy (just adding `Left $`), but the updates to Generator took the rest of our time.

In that file, we now had to care if we were dealing with Files or Directories, as well as add more info when writing the checksum file so we knew what we were reading back in. Instead of just a `FilePath` (serialized as a `String` by Aeson), we now write a tuple which tells us if the FP is a `"file"` or a `"dir"`. Sample:

```
[
    [
        "aa1bd54732b015158d24c55e03bc79b2f211109bc2b0478d6f2ad6b52d15847f",
        [
            "file",
            "web-app/README.md"
        ]
    ],
    [
        "957e98c79e0d021dd3a21f2bce313bc58c164723d78172918577a032f8764bf5",
        [
            "file",
            "web-app/package.json"
        ]
    ],
...
```

We are now in a position to do next week what we wanted to do today, implement `dryRun` for `CopyDirFileDraft` :D c'est la vie, but still good progress and we are compiling again!

**Comment by shayneczyzewski** [comment] 2022-02-03 18:12
Today, we spent about half our allotted time talking about a PR. However, we did have time to finalize `dryRun` for `CopyDirFileDraft` as planned. The approach we took is to get all the files in the directory (recursively), calculate their individual file checksums, and then calculate the checksum of those checksums in aggregate.

We then spent a bit of time refactoring that definition from:
```haskell
dryRun :: w -> IO (Checksum, FileOrDirPathRelativeTo ProjectRootDir)
```

to:
```haskell
getChecksum :: w -> IO Checksum
```

since we now have `getDstPath` available to us. The plan for next week is to fix all the places we just broke. 😄 However, we are getting closer, and it is getting better each session. 🚀

**Comment by shayneczyzewski** [comment] 2022-02-07 13:19
FYI squashed and rebased master, so you will need to reset hard to origin before next time 👍🏻

**Comment by Martinsos** [comment] 2022-02-10 20:13
Nice @shayneczyzewski and using `fswatch` sounds fun!

So when you change the route `to:`, only one file is generated/changed, right?

**Comment by shayneczyzewski** [comment] 2022-02-10 20:39
> Nice @shayneczyzewski and using `fswatch` sounds fun!
> 
> So when you change the route `to:`, only one file is generated/changed, right?

Sorta... I elided the others that change during _every_ compilation though, and only highlighted the deltas in the subsequent examples. So here is the full output:

```
/Users/shayne/dev/wasp/waspc/examples/todoApp/.wasp/out/.waspchecksums
/Users/shayne/dev/wasp/waspc/examples/todoApp/.wasp/out/web-app/src/router.js 👈
/Users/shayne/dev/wasp/waspc/examples/todoApp/.wasp/out/server/src/.copyFile16894-0.tmp
/Users/shayne/dev/wasp/waspc/examples/todoApp/.wasp/out/server/src/server.js
/Users/shayne/dev/wasp/waspc/examples/todoApp/.wasp/out/server/src/server.js
/Users/shayne/dev/wasp/waspc/examples/todoApp/.wasp/out/.waspinfo
/Users/shayne/dev/wasp/waspc/examples/todoApp/.wasp/out/.waspchecksums
```

And I changed it to a`Page` that already existed. Seems like checksum file shows twice for deletion and addition, waspinfo is updated, and server.js is probably removed/added.

**Comment by shayneczyzewski** [comment] 2022-02-17 15:51
Today we pulled out all the checksum logic (incl the writing/deleting of files) into its own module (`Wasp.Generator.WriteFileDrafts`) and refactored some nested pure logic to make it more testable. We started implementing some tests. 🤖  🚀

**Comment by shayneczyzewski** [comment] 2022-02-24 15:19
Spent today writing more tests for `Wasp.Generator.WriteFileDrafts`! Got to use infinite lists and some core vanilla Haskell/FP 🥳

**Closed** 2022-03-15 11:43 UTC
Labels: enhancement
