### ISSUE TITLE
Code blocks in blog re-render to be single line when hovering logo

### ISSUE THREAD

**Issue by Sleavely** [wasp-lang/wasp#1515] opened 2023-10-17 15:42 UTC
I was reading your recent blog post and had trouble following along until I realized code blocks are shrunk because I accidentally hovered my mouse over the logo at some point:

![](https://i.imgur.com/fxfFnks.gif)

...this is probably the weirdest bug I've encountered today. 😂

**Comment by Martinsos** [comment] 2023-10-17 16:15
> Oh wow ok this is crazy @Sleavely :D. I agree, this is the craziest bug I have seen for some time :D!
> 
> Thanks for reporting this -> I am though having a bit of problems replicating it. I just tried it on Chrome on Linux (Gnome on Xorg) and this problem doesn't seem to happen. Could you please share your setup, and any additional details you think might help with replicating it?

@Sleavely I take that back, I just managed to replicate it! I am not sure why it wouldn't happen the first time, but now I got it happening. 
Seems that newlines get ignored. We are using Docusaurus, I wonder if this is somehow connected to them, or if it some of our custom code misbehaving. This will be interesting to debug!

**Comment by Martinsos** [comment] 2023-10-17 16:18
To make it even weirder, I figured out why I couldn't replicate it at first.
So, if you come to the blog post by clicking on it on the https://wasp-lang.dev/blog page, then this bug doesn't manifest.
If you refresh the blog post, or if you come directly to it via its direct URL, then the bug manifests itself!

**Comment by khanjanSanghavi** [comment] 2023-10-25 17:19
Hey, @Martinsos  I want to give it a shot!! 
You learn something new about this bug?
or
Can you say what might be creating this kind of crazy bug?

**Comment by Martinsos** [comment] 2023-10-26 10:57
> Hey, @Martinsos I want to give it a shot!! You learn something new about this bug? or Can you say what might be creating this kind of crazy bug?

Yes sure go for it, but I have to be honest I have no idea! That is what makes it quite fun :D.

Our docs are implemented via Docusaurus -> so maybe it is something Docusaurus related? But I somehow doubt it. So after mouse goes over that logo, something changes permanently. But why would something change permanently just upon hovering over something? Maybe if it changed temporarily, but permanently? Super weird. Almost sounds like we are triggering some kind of bug not caused by us?
Also, why would newlines get messed up? Should we look into the component we have for rendering the code -> I am not sure what we are using there -> and see if whatever we are using has similar bug documented on their github?

Tricky!

**Comment by Martinsos** [comment] 2023-11-14 13:25
Fixed by #1552

**Closed by Martinsos** 2023-11-14 13:25 UTC
Labels: documentation, shouldfix
