### ISSUE TITLE
Is arm64 supported for the docker image?

### ISSUE THREAD

**Issue by JorgeN118** [wasp-lang/wasp#2102] opened 2024-06-15 09:51 UTC
**Describe the bug**
I built the image on my `Apple M2 Pro - arm64`. However, after some minutes of running the docker image locally, the container exits i.e crashes with `SIGSEGV`, at some random point. I guess this due to the fact that wasp does not support yet arm64 architecture. I also noticed that on [fly.io](https://community.fly.io/t/are-arm64-fly-machines-available/5902) there is no arm64 support yet

**To Reproduce**
Steps to reproduce the behavior on a Mac M2:
1. `wasp build`
2. `docker build ... # I build it using arm64 architecture`

**Desktop (please complete the following information):**
 - OS: 14.4.1 
 - Docker version 26.0.0
 - Version Apple M2 Pro

**Comment by Martinsos** [comment] 2024-06-17 14:59
@JorgeN118 pls check out #2003 -> if I remember correctly, we at some determined that our default Dockerfile doesn't work for ARM, and haven't yet got to improving that.

I am closing this one at the moment as the duplicate of #2003 , but please provide any additional info there and take a look if anythign from there might help!

**Closed by Martinsos** 2024-06-17 14:59 UTC
