### ISSUE TITLE
inform users which ENV VARS get set by `wasp deploy fly launch`

### ISSUE THREAD

**Issue by vincanger** [wasp-lang/wasp#2055] opened 2024-05-24 09:10 UTC
it's unclear which (server) ENV VARS are set automatically and which VARS users need to set themselves when deploying via `wasp deploy fly launch`.

Since Wasp automatically sets the following vars (below) via the deploy command, it would be best if we informed the user about this:

- [ ] in the ["Deployment" docs](https://wasp-lang.dev/docs/advanced/deployment/cli)
- [ ] in the ["Env Variable" docs](https://wasp-lang.dev/docs/project/env-vars)
- [ ] in the console after running `wasp deploy fly launch`

---

https://github.com/wasp-lang/wasp/blob/main/waspc/packages/deploy/src/providers/fly/setup/setup.ts#L116
```ts
const secretsArgs = [
        `JWT_SECRET=${randomString}`,
        // NOTE: Normally these would just be envars, but flyctl
        // doesn't provide a way to set envars that persist to fly.toml.
        'PORT=8080',
        `WASP_WEB_CLIENT_URL=${deploymentInfo.clientUrl}`,
        `WASP_SERVER_URL=${deploymentInfo.serverUrl}`,
    ];
```

**Comment by Martinsos** [comment] 2024-05-24 10:32
Duplicate of #2053, so I will close it, but I will copy your comment there because it provides extra ideas.

**Closed** 2024-05-24 10:33 UTC
Labels: documentation, deployment
