### ISSUE TITLE
tsconfig.json(2,14): error TS6053: File '@tsconfig/node18/tsconfig.json' not found

### ISSUE THREAD

**Issue by sammo** [wasp-lang/wasp#2085] opened 2024-06-06 12:40 UTC
Hi - 

I'm trying to start a new wasp project but running into this error on `wasp db migrate-dev` command.

Do you know what the issue could be?

✅ --- Database successfully set up. ----------------------------------------------

🐝 --- Building SDK... ------------------------------------------------------------

[  Wasp  ] tsconfig.json(2,14): error TS6053: File '@tsconfig/node18/tsconfig.json' not found.
[  Wasp  ] ../../../../node_modules/@testing-library/jest-dom/types/jest.d.ts(1,23): error TS2688: Cannot find type definition file for 'jest'.
[  Wasp  ] ../../../../node_modules/@testing-library/jest-dom/types/jest.d.ts(9,27): error TS2304: Cannot find name 'expect'.
[  Wasp  ] ../../../../node_modules/vitest/node_modules/vite/dist/node/index.d.ts(5,41): error TS2307: Cannot find module 'rollup/parseAst' or its corresponding type declarations.
[  Wasp  ]   There are types at '.../mySaasApp/node_modules/vitest/node_modules/rollup/dist/parseAst.d.ts', but this result could not be resolved under your current 'moduleResolution' setting. Consider updating to 'node16', 'nodenext', or 'bundler'.

❌ --- [Error] Your wasp project failed to compile: -------------------------------

- SDK build failed with exit code: 2

❌ --- [Error] Compilation of wasp project failed: --------------------------------

1 errors found

**Comment by Martinsos** [comment] 2024-06-10 11:34
One more user report the same issue: https://github.com/wasp-lang/open-saas/issues/173 .

@aliammari1, it could help if you could provide following info: your OS, wasp version, node version, how did you start the project (open saas? specific template? Mage?).

In the meantime, pls try running `wasp clean` and see if that helps -> if it does, let us know.

**Comment by Martinsos** [comment] 2024-06-10 11:43
@grsh50 , could you please try switching to node 20 (e.g. using `nvm`) and try running Wasp again?

@aliammari1 which node version are you using? If you are using 18, could you also try switching to 20 and tell us if that helps?

**Comment by grsh50** [comment] 2024-06-10 12:36
```
grosh@buh:~/Documents/src/repo/newWasp/myTodoApp$ wasp db migrate-dev

🐝 --- Compiling wasp project... --------------------------------------------------


✅ --- Successfully completed npm install. ----------------------------------------


🐝 --- Setting up database... -----------------------------------------------------


[   Db  !] Error: P1003
[   Db  !] 
[   Db  !] Database dev.db does not exist at /home/grosh/Documents/src/repo/newWasp/myTodoApp/.wasp/out/db/./dev.db
[   Db  !] 
✅ --- Database successfully set up. ----------------------------------------------


🐝 --- Building SDK... ------------------------------------------------------------


[  Wasp  ] tsconfig.json(2,14): error TS6053: File '@tsconfig/node18/tsconfig.json' not found.
[  Wasp  ] ../../../../node_modules/@testing-library/jest-dom/types/jest.d.ts(1,23): error TS2688: Cannot find type definition file for 'jest'.
[  Wasp  ] ../../../../node_modules/@testing-library/jest-dom/types/jest.d.ts(9,27): error TS2304: Cannot find name 'expect'.
[  Wasp  ] ../../../../node_modules/vitest/node_modules/vite/dist/node/index.d.ts(5,41): error TS2307: Cannot find module 'rollup/parseAst' or its corresponding type declarations.
[  Wasp  ]   There are types at '/home/grosh/Documents/src/repo/newWasp/myTodoApp/node_modules/vitest/node_modules/rollup/dist/parseAst.d.ts', but this result could not be resolved under your current 'moduleResolution' setting. Consider updating to 'node16', 'nodenext', or 'bundler'.

❌ --- [Error] Your wasp project failed to compile: -------------------------------

- SDK build failed with exit code: 2


❌ --- [Error] Compilation of wasp project failed: --------------------------------

1 errors found
grosh@buh:~/Documents/src/repo/newWasp/myTodoApp$ node --version
v20.14.0

```

**Comment by Martinsos** [comment] 2024-06-10 14:27
Ok so it also happens with node `20`, didn't expect that! Thanks, we will be looking into this in the following days and will be posting updates here!

**Comment by Martinsos** [comment] 2024-06-10 14:41
Note for devs: I tried replicating this on my machine but failed, all works so far. Specifically, I reinstalled latest version of Wasp and ran `wasp new MyTestApp -t todo-ts` and then `wasp db migrate-dev`. I also tried cleaning the whole npm cache with `npm cache clean --force` to simulate a more "fresher" situation, but that also didn't help, it still works.
I did this first test with node 20, I tried doing it also with node 18.19 but also couldn't replicate. This is on Arch Linux.

**Comment by aliammari1** [comment] 2024-06-10 14:51
> @grsh50 , could you please try switching to node 20 (e.g. using `nvm`) and try running Wasp again?
> 
> @aliammari1 which node version are you using? If you are using 18, could you also try switching to 20 and tell us if that helps?

thank you sir, the problem was my node version. I updated it from 18 to 20 and it worked

**Comment by Martinsos** [comment] 2024-06-10 17:35
> > @grsh50 , could you please try switching to node 20 (e.g. using `nvm`) and try running Wasp again?
> > @aliammari1 which node version are you using? If you are using 18, could you also try switching to 20 and tell us if that helps?
> 
> thank you sir, the problem was my node version. I updated it from 18 to 20 and it worked

Thanks for letting me know!

This does make things even more complex though hah, because one user got it fixed by installing another template, while one user fixed it with using another node version, and finally none of these helped third user! Hm. Almost sounds like it is getting fixed randomly.

**Comment by Martinsos** [comment] 2024-06-12 14:56
> Thank you for your support! :)
> 
> I ran `wasp new todo -t todo-ts`, and it worked.
> 
> This time, compiling the Wasp project took longer, but the SDK build was almost instant.
> 
> Could the issue be related to the Node version used to create the new project? The previous logs were from a project created on Node 18.19, and only the `wasp db migrate-dev` command was executed on Node 20.14.
> 
> Update: The MAGE app now runs.

Oh that's an interesting hypothesis indeed!

AHa, wait, now even the older app runs? Ok, now we have no idea again what is causing this :D. 

Is there any way you can replicate the initial problem again? For example going to node 18 again, and trying to run that Mage app, or maybe new app based on `todo-ts`?

@sammo above managed to replicate it doing `wasp new MyCoolApp -t todo-ts` with node 18, if you can also do that consistently, that gives us something solid to work from.

**Comment by Martinsos** [comment] 2024-06-13 16:40
One more report: https://discord.com/channels/686873244791210014/1250815248395669504/1250815248395669504 .

User was using node 18, but new data point is that they managed to fix it by adding 
```
 "devDependencies": {
    "@tsconfig/node18": "latest",
```
to their package.json.

What also worked was switching to node 20, then that dev dependency was not needed, same like other users.

**Comment by grsh50** [comment] 2024-06-13 23:15
I ran some test builds with `todo's` and `saas` templates on `node` versions `18.19.0` and `18.19.1` and everything works fine.

**Comment by Martinsos** [comment] 2024-06-14 12:23
> I ran some test builds with `todo's` and `saas` templates on `node` versions `18.19.0` and `18.19.1` and everything works fine.

Ah come on :)! I am kidding, thanks a lot, but am still surprised by inconsistency of this bug. Still, we will figure it out, one way or another!

**Comment by infomiho** [comment] 2024-06-27 08:42
This is the only similar issue I found while searching around the internet: https://github.com/TypeStrong/ts-node/issues/2076

It seems to be related to `ts-node` which `jest` uses under the hood to resolve the `tsconfig.json`. This was caused by some internal API changes in TS 5.2+ version. I'm really not sure if we have similar issues as reported there. I've tested also on Ubuntu with Node 18 and couldn't reproduce it.

**Comment by Martinsos** [comment] 2024-06-27 09:08
> This is the only similar issue I found while searching around the internet: [TypeStrong/ts-node#2076](https://github.com/TypeStrong/ts-node/issues/2076)
> 
> It seems to be related to `ts-node` which `jest` uses under the hood to resolve the `tsconfig.json`. This was caused by some internal API changes in TS 5.2+ version. I'm really not sure if we have similar issues as reported there. I've tested also on Ubuntu with Node 18 and couldn't reproduce it.

It being triggered by changes in TS version makes sense, as it started happened suddenly, that is very likely the cause! We need to pin down that TS version tighter.

I would still like to better understand the exact thing that happens, but I think we have a good bet what is the cause now.

**Comment by sodic** [comment] 2024-07-02 15:32
> It seems to be related to ts-node which jest uses under the hood to resolve the tsconfig.json.


That's not it (at least I think it isn't). `ts-node` is nowhere to be found in `node_modules`. From what I see, Jest isn't using it. 

@infomiho What made you think we were using `ts-node`?
If it was [this comment](https://github.com/TypeStrong/ts-node/issues/2076#issuecomment-1825505277), it was probably a misunderstanding - the comment talks about Jest TS configuration files (not tsconfig.json files).

Regardless, I tried installing `ts-node` both globally and in the repo, with the hopes of `jest` using it if it's available, but no luck. Unless I missed something, I think it's safe to say this isn't related to `ts-node`.

I'll now try reproducing it with different versions of TypeScript.

**Comment by sodic** [comment] 2024-07-03 09:53
Next time this happens, we should ask our users for a zip of their projects (or at least their `package.json` and  `package-lock.json` files).

**Comment by Martinsos** [comment] 2024-07-03 12:54
@sodic it is not any kind of special projects though, they say above they merely had it happen on creating a new Wasp project from the template. So maybe package-lock.json files would offer something unique for their installation, but the rest, including package.json, shouldn't be anything unique. Notice that even if they share their package-lock.json, it still won't capture what was installed for the purposes of the framework code (or will it?).

**Comment by Martinsos** [comment] 2024-07-03 15:53
Some quick analysis of information we have so far:
- OS: Ubuntu, Debian, unknown, unknown
- everybody had the issue due to creating a Wasp project with `node 18`.
- different fixes that worked for people:
  - `wasp clean` && `wasp new -t saas` while staying on `node 18`
  - switching to `node 20` and running the project again
  - creating project again with `node 20` and then running it
  - adding `tsconfig/node18` directly to package.json as a dev dep
- once things get working for people, they continue working

It seems that there is a situation, when using `node 18`, that results in `tsconfig/node18` not getting installed, and then stuff fails. And it seems that to get out of it, you need to shake things up a bit, and the most efficient way is to switch to `node 20`, but it seems like sometimes something else also helps.

**Comment by sodic** [comment] 2024-07-03 16:07
Ideas:
- The file most likely really is missing (i.e., it's not an error in the code trying to find the file) because:
  1. TSC crashes immediately after not being able to find the file
  2. One user added it to devDependencies at the root of the project, which fixed the problem immediately.
- Our best guess is that, sometimes, the `@tscofig/node18` doesn't get installed to `node_modules`.

Other thoughts:
- The SDK lists `tsconfig/node18` as a `devDependency`. How come it's ever installed (`devDependencies` shouldn't be installed for packages)? Is it because it's a linked package?
- The server also lists `tsconfig/node18` as a `devDependency`. I forgot how NPM install works if the package is already installed in scope (I think it just duplicates it)?
- The central question: Why do we ever get `tsconfig/node18` installed in top-level `node_modules`. Do we just get lucky that some other package includes it as a regular dependency? Does NPM install devDependencies for SDK? Does this also happen in production?

One problem I noticed:
- It seems we treat the SDK as a dependency (i.e., we don't run `npm install` inside its folder, it's installed indirectly through the root package.json), but we also treat it as a project (i.e., we build it). This is wrong and might be related to this problem. In other words, `tsconfig/node18` is possibly being installed by luck.

**Comment by sodic** [comment] 2024-07-04 08:08
For users running into this: Please zip the entire project that exhibits this behavior and send it to us :)

**Comment by Moamethic** [comment] 2024-07-16 20:20
Hi
I tried everything discussed here and nothing worked for me, so here is the download link to my project zip:
https://mega.nz/file/YH1AgBLa#URDfK1Pyv0zpD8JcoZz-OqxJIx_o-YrMTjSjH3w7PO8

P.S: Sorry for the large file size, I just included everything for better diagnosis.

**Comment by infomiho** [comment] 2024-07-16 20:50
@Moamethic Hey, thank you for the info. Could you share the error message you see?

**Comment by Moamethic** [comment] 2024-07-16 20:52
> @Moamethic Hey, thank you for the info. Could you share the error message you see?

Sure.

`🐝 --- Building SDK... ------------------------------------------------------------


[  Wasp  ] tsconfig.json(2,14): error TS6053: File '@tsconfig/node18/tsconfig.json' not found.
[  Wasp  ] ../../../../node_modules/@testing-library/jest-dom/types/jest.d.ts(1,23): error TS2688: Cannot find type definition file for 'jest'.
[  Wasp  ] ../../../../node_modules/@testing-library/jest-dom/types/jest.d.ts(9,27): error TS2304: Cannot find name 'expect'.
[  Wasp  ] ../../../../node_modules/vitest/node_modules/vite/dist/node/index.d.ts(5,41): error TS2307: Cannot find module 'rollup/parseAst' or its corresponding type declarations.
[  Wasp  ]   There are types at '/root/my-proj/app/node_modules/vitest/node_modules/rollup/dist/parseAst.d.ts', but this result could not be resolved under your current 'moduleResolution' setting. Consider updating to 'node16', 'nodenext', or 'bundler'.

❌ --- [Error] Your wasp project failed to compile: -------------------------------

- SDK build failed with exit code: 2


❌ --- [Error] Compilation of wasp project failed: --------------------------------

1 errors found`

**Comment by infomiho** [comment] 2024-07-16 21:09
And also, which Node version and Wasp version are you using? Thank you for reporting this 👍 

Until we find out the root cause, did you maybe try using Node 20 + running `wasp clean` and `wasp start` again?

**Comment by Moamethic** [comment] 2024-07-16 21:18
> And also, which Node version and Wasp version are you using? Thank you for reporting this 👍
> 
> Until we find out the root cause, did you maybe try using Node 20 + running `wasp clean` and `wasp start` again?

At first I was using node 18, then I installed nvm and tried with node 20 using ```wasp clean```, but the issue still persists. I installed wasp using ```curl -sSL https://get.wasp-lang.dev/installer.sh | sh``` two hours ago, so I'm using the current latest version for sure. And I run it on Ubuntu 24.04.

**Comment by Martinsos** [comment] 2024-07-22 12:05
Another one: https://discord.com/channels/686873244791210014/1263530383379796111/1263615673678958612

**Comment by Martinsos** [comment] 2024-07-24 10:00
Another hit: https://discord.com/channels/686873244791210014/1265303458626539523/1265303458626539523 .

**Comment by sodic** [comment] 2024-07-26 11:52
@Moamethic Hey, I'm looking at your code now.

Can you maybe share the NPM version you used when you hit the bug (if you remember)?

**Comment by Moamethic** [comment] 2024-07-26 11:55
> @Moamethic Hey, I'm looking at your code now.
> 
> Can you maybe share the NPM version you used when you hit the bug (if you remember)?

Unfortunately I don't remember.

**Comment by santolucito** [comment] 2024-08-08 10:25
> What also worked was switching to node 20, then that dev dependency was not needed, same like other users.

I also ran into the issue on Node 18, and switching to Node 20 fixed it

**Comment by sodic** [comment] 2024-08-08 13:57
@santolucito Please tell me you remember your NPM version :pray:

**Comment by santolucito** [comment] 2024-08-08 14:06
I have no idea. I had spun up a Digital Ocean server and went through the install steps normally. I can redo this if you quickly and check things. Just let me know what you want to know.

**Comment by sodic** [comment] 2024-08-08 14:43
@santolucito If you could reproduce the bug in a Digital Ocean setup, tell me the versions of:
- node
- npm
- wasp

And zip your project code - I'd be eternally grateful! I just hope you'll be able to reproduce it. This bug's pretty hard to catch.

**Comment by santolucito** [comment] 2024-08-08 15:14
@sodic I sent you an email to the email listed on your profile.

**Comment by sodic** [comment] 2024-08-08 15:42
Thanks @santolucito, you're a life-saver!

The bug happens only with NPM versions older  `v9.5.0`. I can reproduce it with any version of Node (`18.x.x` or `20.x.x`).

To fix the problem, update your NPM version to `v9.5.0` or higher. I recommend updating it to the latest version.

In a regular setup:
```bash
npm install -g npm@latest
```
If you're using `nvm`:
```bash
nvm install-latest-npm
```

**Closed** 2024-08-08 15:57 UTC
Labels: bug
