### ISSUE TITLE
Fix inconsistent import extensions in both .wasp file and in JS files.

### ISSUE THREAD

**Issue by sodic** [wasp-lang/wasp#1363] opened 2023-07-26 11:46 UTC
Background: https://github.com/wasp-lang/wasp/issues/812#issuecomment-1335579353

The initial approach explained above turned out to be too confusing - we want to do some magic with the extensions after all. It will spare our documentation from messages such as this one:
![image](https://github.com/wasp-lang/wasp/assets/22752307/6a2c6b4b-f86a-4d4f-a311-4a608538fdf5)

**Comment by craigmc08** [comment] 2023-08-08 17:37
I think we should try to avoid doing magic with extensions, and instead see if we can change how modules are resolved in the generated code:

Inconsistent extensions are confusing not only in the Wasp file, but also across all server-side code, which has the same weird requirement of importing `ts` files with `.js` but even worse: some imports work fine without an extension:

```ts
// Trying to import `./util.ts`
import { helperFn } from './util' // DOESN'T WORK, but VSCode thinks its fine
import { helperFn } from './util.js' // WORKS

// Trying to import `./util/index.js`
import { helperFn } from './util' // DOESNT'T WORK, but VSCode thinks its fine

import { QueryType } from '@wasp/queries/types' // WORKS
import { QueryType } from '@wasp/queries/types.js' // WORKS

// NOTE: Without this use of `helperFn`, both imports work fine.
// I *think* this is because unused imports aren't emitted in the compiled JS code.
// Which leads to some spooky action at a distance: you can be writing code somewhere
// in a file and suddenly your server is crashing due to an import that looked like
// it was working before.
helperFn();
```

Even while testing this I kept tripping over unused imports getting removed!

From the comment @sodic linked:

> Of course, we could always extend our pipeline with a preprocessing tool that takes care of this issue. Still, considering that this is a feature/quirk of the entire ecosystem and is not specific to Wasp, I don't think we should. Given enough time (after the dust settles), people might event start expecting the exact opposite behavior.
>
> Therefore, switching to an older module system that's slowly on its way out (i.e., `commonjs`) isn't an appropriate solution (not to mention the other problems that might cause for the users, such as the lack of support for top-level `await`).

I think the issue is that because the generated code is a several steps away from the user code, when the server says it can't find a module, people might assume that it's Wasp's fault. As an example: https://discord.com/channels/686873244791210014/920312576133443634/1138499244215500831

## Suggestions

1. Configure the server node process to be able to handle imports like `./util`, with no extension. This way, the behavior is no longer confusing.
2. Add another build step to the server code that fixes extensions, as is done on the client (https://github.com/wasp-lang/wasp/pull/1019#discussion_r1116246007). This way, the behavior is no longer confusing.
3. Convince VSCode to not resolve imports like `./util` for server code. This way, the rules are consistent between the editor and the server process.

## Antisuggestions

1. Don't rewrite imports from wasp files to allow using `.ts` to import `@server/*.ts` files. This would result in more inconsistency, so even more confusion.

**Comment by Martinsos** [comment] 2023-09-08 09:35
To quickly recap:
1. .wasp file has different expectations for extensions (.js, .ts, no extension) of external imports depending if they are client or server code -> very confusing.
2. JS/TS code on the client and server also has different expectations for extensions -> client allows no extension or extension, server requires extension, and there are even more considerations regarding if it is .js or .ts.

This is altogether too complicated to track and get right, both us and users keep getting confused with this. We need to make this uniform, and robust.

I believe we should be able to solve this nicely while we are doing restructuring anyway.

**Comment by Martinsos** [comment] 2023-09-08 09:35
Related convo on Discord: https://discord.com/channels/686873244791210014/943092165964349500/1149372212575469618 .

**Comment by Martinsos** [comment] 2024-03-12 18:18
Fixed with restructuring!

**Closed by Martinsos** 2024-03-12 18:18 UTC
Labels: shouldfix
