### ISSUE TITLE
Project failed to compile

### ISSUE THREAD

**Issue by grsh50** [wasp-lang/wasp#2091] opened 2024-06-08 19:23 UTC
**Describe the bug**
I'd followed the getting started from https://wasp-lang.dev/docs/quick-start.
error appears after executing `wasp db migrate-dev`

I get the same error regardless of the project, MAGE genereted app throw same error

**To Reproduce**
I'd followed the getting started from https://wasp-lang.dev/docs/quick-start.
1. `wasp new`
2. `cd MyApp/app`
3. `wasp db start`
4. `wasp db migrate-dev`

```
🐝 --- Compiling wasp project... --------------------------------------------------


✅ --- Successfully completed npm install. ----------------------------------------


🐝 --- Setting up database... -----------------------------------------------------


✅ --- Database successfully set up. ----------------------------------------------


🐝 --- Building SDK... ------------------------------------------------------------


[  Wasp  ] tsconfig.json(2,14): error TS6053: File '@tsconfig/node18/tsconfig.json' not found.
[  Wasp  ] ../../../../node_modules/@testing-library/jest-dom/types/jest.d.ts(1,23): error TS2688: Cannot find type definition file for 'jest'.
[  Wasp  ] ../../../../node_modules/@testing-library/jest-dom/types/jest.d.ts(9,27): error TS2304: Cannot find name 'expect'.
[  Wasp  ] ../../../../node_modules/vitest/node_modules/vite/dist/node/index.d.ts(5,41): error TS2307: Cannot find module 'rollup/parseAst' or its corresponding type declarations.
[  Wasp  ]   There are types at '/home/grosh/Documents/src/repo/newWasp/MyApp/app/node_modules/vitest/node_modules/rollup/dist/parseAst.d.ts', but this result could not be resolved under your current 'moduleResolution' setting. Consider updating to 'node16', 'nodenext', or 'bundler'.

❌ --- [Error] Your wasp project failed to compile: -------------------------------

- SDK build failed with exit code: 2


❌ --- [Error] Compilation of wasp project failed: --------------------------------

1 errors found

```

**Expected behavior**
I can finish the quick start guide :)

**Screenshots**
![Screenshot_20240608_210949](https://github.com/wasp-lang/wasp/assets/62712301/8eb5dbc8-adaf-4f2a-bf2d-6fd73aa27365)

**Desktop (please complete the following information):**
 - OS: Linux 6.1.0-21-amd64 Debian 6.1.90-1 (2024-05-03) x86_64 GNU/Linux
 - Browser: chrome
 - Version: chrome 125.0.6422.141
 - Wasp: 0.13.2
 - Node v18.19.0

**Additional context**

I follow this steps after saas template
```
🐝 --- Creating your project from the "saas" template... --------------------------

Created new Wasp app in ./MyApp directory!

To run your new app, follow the instructions below:

  1. Position into app's root directory:
    cd MyApp/app

  2. Run the development database (and leave it running):
    wasp db start

  3. Open new terminal window (or tab) in that same dir and continue in it.

  4. Apply initial database migrations:
    wasp db migrate-dev

  5. Create initial dot env file from the template:
    cp .env.server.example .env.server

  6. Last step: run the app!
    wasp start

```
checked #2085 and
for `wasp new myTodoApp -t todo-ts` i get same error, even after `wasp clean`

**Comment by Martinsos** [comment] 2024-06-10 11:38
Thanks for this detailed report @grsh50 , all the information you provided helps a lot, awesome!

I will be closing this one as a duplicate of https://github.com/wasp-lang/wasp/issues/2091, but I will be linking it there, and please join us there for the discussion!

**Closed by Martinsos** 2024-06-10 11:38 UTC
