### ISSUE TITLE
my Mage app failed to run after running `wasp start`

### ISSUE THREAD

**Issue by adam7rans** [wasp-lang/wasp#1527] opened 2023-10-20 18:42 UTC
**Describe the bug**
I was able to install everything and start my MAGE wasp app but got this error
```
[plugin:vite:import-analysis] Failed to resolve import "./ext-src/Dashboard.jsx" from "src/router.tsx". Does the file exist?
/Users/8alls/Downloads/Cals-u1ed5/.wasp/out/web-app/src/router.tsx:15:43
7  |  import LoginPage from './ext-src/pages/auth/Login.jsx';
8  |  import SignupPage from './ext-src/pages/auth/Signup.jsx';
9  |  import { Dashboard as DashboardPage } from './ext-src/Dashboard.jsx';
   |                                              ^
10 |  export const routes = {
11 |      LoginRoute: {
    at formatError (file:///Users/8alls/Downloads/Cals-u1ed5/.wasp/out/web-app/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:44062:46)
    at TransformContext.error (file:///Users/8alls/Downloads/Cals-u1ed5/.wasp/out/web-app/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:44058:19)
    at normalizeUrl (file:///Users/8alls/Downloads/Cals-u1ed5/.wasp/out/web-app/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:41844:33)
    at async file:///Users/8alls/Downloads/Cals-u1ed5/.wasp/out/web-app/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:41998:47
    at async Promise.all (index 8)
    at async TransformContext.transform (file:///Users/8alls/Downloads/Cals-u1ed5/.wasp/out/web-app/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:41914:13)
    at async Object.transform (file:///Users/8alls/Downloads/Cals-u1ed5/.wasp/out/web-app/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:44352:30)
    at async loadAndTransform (file:///Users/8alls/Downloads/Cals-u1ed5/.wasp/out/web-app/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:55026:29)
    at async viteTransformMiddleware (file:///Users/8alls/Downloads/Cals-u1ed5/.wasp/out/web-app/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:64430:32
Click outside, press Esc key, or fix the code to dismiss.
You can also disable this overlay by setting server.hmr.overlay to false in vite.config.js.

```

I checked to see if the `router.tsx` file was there and it is there. Here is what is in it.

```
import React from 'react'
import { Route, Switch, BrowserRouter as Router } from 'react-router-dom'
import { interpolatePath } from './router/linkHelpers'
import type {
  RouteDefinitionsToRoutes,
  OptionalRouteOptions,
  ParamValue,
} from './router/types'
import { Layout } from './ext-src/Layout.jsx'

import createAuthRequiredPage from "./auth/pages/createAuthRequiredPage"

import LoginPage from './ext-src/pages/auth/Login.jsx'
import SignupPage from './ext-src/pages/auth/Signup.jsx'
import { Dashboard as DashboardPage } from './ext-src/Dashboard.jsx'


export const routes = {
  LoginRoute: {
    to: "/login",
    component: LoginPage,
    build: (
      options?: OptionalRouteOptions,
    ) => interpolatePath("/login", undefined, options.search, options.hash),
  },
  SignupRoute: {
    to: "/signup",
    component: SignupPage,
    build: (
      options?: OptionalRouteOptions,
    ) => interpolatePath("/signup", undefined, options.search, options.hash),
  },
  DashboardRoute: {
    to: "/",
    component: createAuthRequiredPage(DashboardPage),
    build: (
      options?: OptionalRouteOptions,
    ) => interpolatePath("/", undefined, options.search, options.hash),
  },
} as const;

export type Routes = RouteDefinitionsToRoutes<typeof routes>

const router = (
  <Router>
    <Layout>
    <Switch>
      {Object.entries(routes).map(([routeKey, route]) => (
        <Route
          exact
          key={routeKey}
          path={route.to}
          component={route.component}
        />
      ))}
    </Switch>
    </Layout>
  </Router>
)

export default router

export { Link } from './router/Link'
```

**Comment by Martinsos** [comment] 2023-10-23 13:05
Mage apps can have errors due to GPT.

Do you have Dashboard.jsx file? Where is it located? Which symbol does it export, DashboardPage or Dashboard? One of those things is probably wrong.

**Comment by adam7rans** [comment] 2023-10-23 17:18
> Mage apps can have errors due to GPT.
> 
> Do you have Dashboard.jsx file? Where is it located? Which symbol does it export, DashboardPage or Dashboard? One of those things is probably wrong.

Dashboard.jsx is located in 

`/src/client/pages`

and the file contains

```
import React, { useState } from 'react';
import { useQuery } from '@wasp/queries';
import { useAction } from '@wasp/actions';
import getFoods from '@wasp/queries/getFoods';
import createFood from '@wasp/actions/createFood';
import getMeals from '@wasp/queries/getMeals';
import createMeal from '@wasp/actions/createMeal';

export function Dashboard() {
  const { data: foods, isLoading: isLoadingFoods, error: errorFoods } = useQuery(getFoods);
  const { data: meals, isLoading: isLoadingMeals, error: errorMeals } = useQuery(getMeals);
  const createFoodFn = useAction(createFood);
  const createMealFn = useAction(createMeal);
  const [foodName, setFoodName] = useState('');
  const [caloriesPer100g, setCaloriesPer100g] = useState(0);
  const [selectedFood, setSelectedFood] = useState(null);
  const [quantity, setQuantity] = useState(0);

  if (isLoadingFoods || isLoadingMeals) return 'Loading...';
  if (errorFoods || errorMeals) return 'Error: ' + (errorFoods || errorMeals);

  const handleAddFood = () => {
    createFoodFn({ name: foodName, caloriesPer100g });
    setFoodName('');
    setCaloriesPer100g(0);
  };

  const handleAddMeal = () => {
    createMealFn({ foodId: selectedFood.id, quantity });
    setSelectedFood(null);
    setQuantity(0);
  };

  return (
    <div className='p-4'>
      <div className='flex gap-x-4 py-5'>
        <input
          type='text'
          placeholder='Food Name'
          className='px-1 py-2 border rounded text-lg'
          value={foodName}
          onChange={(e) => setFoodName(e.target.value)}
        />
        <input
          type='number'
          placeholder='Calories per 100g'
          className='px-1 py-2 border rounded text-lg'
          value={caloriesPer100g}
          onChange={(e) => setCaloriesPer100g(Number(e.target.value))}
        />
        <button
          onClick={handleAddFood}
          className='bg-blue-500 hover:bg-blue-700 px-2 py-2 text-white font-bold rounded'
        >
          Add
        </button>
      </div>
      <div className='grid grid-cols-4 gap-4'>
        <div className='col-span-2'>
          <table className='w-full'>
            <thead>
              <tr>
                <th>Food Name</th>
                <th>Quantity (g)</th>
                <th>Total Calories</th>
                <th>Calorie Amount</th>
              </tr>
            </thead>
            <tbody>
              {meals.map((meal) => (
                <tr key={meal.id}>
                  <td>{meal.food.name}</td>
                  <td>{meal.quantity}</td>
                  <td>{meal.food.caloriesPer100g}</td>
                  <td>{meal.quantity * (meal.food.caloriesPer100g / 100)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        <div className='col-span-2'>
          <table className='w-full'>
            <thead>
              <tr>
                <th>Food Name</th>
              </tr>
            </thead>
            <tbody>
              {foods.map((food) => (
                <tr
                  key={food.id}
                  onClick={() => setSelectedFood(food)}
                  className={selectedFood && selectedFood.id === food.id ? 'bg-gray-200' : ''}
                >
                  <td>{food.name}</td>
                </tr>
              ))}
            </tbody>
          </table>
          {selectedFood && (
            <div className='mt-4'>
              <input
                type='number'
                placeholder='Quantity (g)'
                className='px-1 py-2 border rounded text-lg'
                value={quantity}
                onChange={(e) => setQuantity(Number(e.target.value))}
              />
              <button
                onClick={handleAddMeal}
                className='bg-blue-500 hover:bg-blue-700 px-2 py-2 text-white font-bold rounded'
              >
                Add Meal
              </button>
            </div>
          )}
        </div>
      </div>
      <div className='fixed bottom-0 left-0 right-0 bg-gray-200 p-4'>
        TOTAL: {meals.reduce((total, meal) => total + (meal.quantity * (meal.food.caloriesPer100g / 100)), 0)}
      </div>
    </div>
  );
}%  
```

**Comment by Martinsos** [comment] 2023-10-25 09:22
Thanks for sharing! So the problem is that Mage (GPT) made a mistake in your main.wasp file -> it provided path to that page while committing `pages/` part of the paths.
Look for your `page DashboardPage` or similar declaration and look for `component:` part, that path there needs to contain `pages/` part in it, same like `page LoginPage` and `page SignupPage` have it.

I will be closing this issue for now, and for future help, I suggest you aks for help on our [Discord](https://discord.com/invite/rzdnErX), as this is not really an issue with the Wasp / Mage, but is instead a support in using Mage. We have "questions" part there where you can get help for stuff like this faster!

**Closed by Martinsos** 2023-10-25 09:22 UTC
