### ISSUE TITLE
Fix esbuild 0.24.1 issue

### ISSUE THREAD

**Issue by AlperGurel** [wasp-lang/wasp#2425] opened 2024-12-20 09:53 UTC
**Describe the bug**
`wasp start ` command fails on a newly created example to do project. With this error. I have been using wasp for over a month now, my project failed today with an error. When I try new project from wasp, it also failed. 

**To Reproduce**
1. Enter `wasp new` in terminal.

2. Select todo-ts app by pressing 2 and enter.
3. Type `wasp db migrate-dev`
4. Type `wasp start`

**Expected behavior**
I should be able to see the app start successfully.

**Screenshots**
<img width="1053" alt="Image" src="https://github.com/user-attachments/assets/87943dc1-c352-4e72-b72f-85cc83cb26fd"  />

[![Image](https://github.com/user-attachments/assets/87943dc1-c352-4e72-b72f-85cc83cb26fd)](https://github.com/user-attachments/assets/87943dc1-c352-4e72-b72f-85cc83cb26fd)

**Desktop (please complete the following information):**
 - Macos Sonama (M2 Chip)

**Additional context**
People over internet mention it is an esbuild problem so they were able to solve it by downgrading esbuild, but it didn't work for me.

**Comment by infomiho** [comment] 2024-12-20 10:13
I can confirm this also happens what I do the steps you described 👍 

Esbuild team track this here: https://github.com/evanw/esbuild/issues/4010
Vite team tracks this here: https://github.com/vitejs/vite/issues/19018

It should be fixed by this PR: https://github.com/evanw/esbuild/pull/4013 (I suppose this will be then released in the next `esbuild` release).

Let's see if this get released today and that should be it. If it doesn't happen, we should quickly patch this since Wasp is now _broken_ and you can't really work on new apps!

**Comment by hugomartinet** [comment] 2024-12-20 11:07
Hi @infomiho,
Thanks for your report! Do you know of a way to bypass this issue in the meantime? Can we somehow tell wasp to use a previous version of `esbuild`?

I tried 2 options, but none worked..

**1. Forcing `vite` version to a previous version**

```json
{
  "name": "my-app",
  "dependencies": {
    ...
  },
  "devDependencies": {
    ...
    "vite": "4.2.0"
  }
}

```

**2. Overriding `esbuild` version in the `vite` dependencies**

```json
{
  "name": "my-app",
  "dependencies": {
    ...
  },
  "devDependencies": {
   ...
  },
  "overrides": {
    "vite": {
      "esbuild": 0.24.0
    }
  }
}

```

**Comment by patak-dev** [comment] 2024-12-20 11:45
vite@6.0.5 is out pinning to esbuild 0.24.0 until this is fixed in esbuild, you can update to vite instead of doing the override

**Comment by infomiho** [comment] 2024-12-20 15:32
Thank you @patak-dev! This fixed our problem now :) 

Wasp now works again @AlperGurel but we are still going to look into pinning some of our deps (e.g. Vite or our Rollup plugin for bundling the server) in the future.

**Closed by infomiho** 2024-12-20 15:32 UTC
